CREATE TABLE "PROJECT1"."LOGIN" 
   (	"USERNAME" VARCHAR2(15 BYTE), 
	"PASSWORD" VARCHAR2(15 BYTE) NOT NULL ENABLE;
	
CREATE TABLE "PROJECT1"."CATEGORY" 
   (	"CATEGORY_ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IMAGE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("CATEGORY_ID"),
	  CONSTRAINT "CATEGORY_UK1" UNIQUE ("NAME");

CREATE TABLE "PROJECT1"."PLACES" 
   (	"PLACE_ID" NUMBER, 
	"NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"IMAGE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"LOCATION" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CATEGORY_ID" NUMBER, 
	 CONSTRAINT "PLACES_PK" PRIMARY KEY ("PLACE_ID"),
	 CONSTRAINT "PLACES_UK1" UNIQUE ("NAME"),
	  CONSTRAINT "PLACES_FK1" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "PROJECT1"."CATEGORY" ("CATEGORY_ID") ON DELETE CASCADE ENABLE;

CREATE SEQUENCE  "PROJECT1"."CATEGORY_SEQUENCE"  MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 
		START WITH 21 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE SEQUENCE  "PROJECT1"."PLACES_SEQUENCE"  MINVALUE 101 MAXVALUE 200 INCREMENT BY 1 
		START WITH 121 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;